import { Subject } from '@/types'

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: 1,
    code: 'CS101',
    name: 'Introduction to Computer Science',
    department: 'Computer Science',
    description:
      'Fundamental concepts of computer science, including algorithms, data structures, and programming basics.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    code: 'IT201',
    name: 'Network Fundamentals',
    department: 'Information Technology',
    description: 'Basic principles of computer networks, protocols, and network architecture.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    code: 'SE301',
    name: 'Software Design Patterns',
    department: 'Software Engineering',
    description:
      'Study of common software design patterns and their applications in real-world projects.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    code: 'EE210',
    name: 'Circuit Analysis',
    department: 'Electrical Engineering',
    description: 'Analysis of electrical circuits, including AC/DC theory and circuit components.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    code: 'ME220',
    name: 'Thermodynamics',
    department: 'Mechanical Engineering',
    description: 'Introduction to thermodynamic principles and their engineering applications.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    code: 'CE101',
    name: 'Structural Engineering Basics',
    department: 'Civil Engineering',
    description: 'Fundamentals of structural analysis and design in civil engineering.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    code: 'DSAI110',
    name: 'Machine Learning Foundations',
    department: 'Data Science & Artificial Intelligence',
    description:
      'Core concepts of machine learning, supervised and unsupervised learning algorithms.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    code: 'CYB101',
    name: 'Introduction to Cyber Security',
    department: 'Cyber Security',
    description: 'Overview of cyber security principles, threats, and protection mechanisms.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 9,
    code: 'MATH101',
    name: 'Calculus I',
    department: 'Mathematics',
    description: 'Differential and integral calculus with applications.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 10,
    code: 'PHY101',
    name: 'General Physics',
    department: 'Physics',
    description:
      'Fundamental concepts in classical mechanics, thermodynamics, and electromagnetism.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    code: 'CHEM101',
    name: 'General Chemistry',
    department: 'Chemistry',
    description:
      'Basic principles of chemistry, including atomic structure and chemical reactions.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 12,
    code: 'BA101',
    name: 'Principles of Management',
    department: 'Business Administration',
    description: 'Introduction to management theories, practices, and organizational behavior.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 13,
    code: 'AF201',
    name: 'Financial Accounting',
    department: 'Accounting & Finance',
    description: 'Fundamentals of financial accounting, reporting, and analysis.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 14,
    code: 'ECON101',
    name: 'Microeconomics',
    department: 'Economics',
    description: 'Study of individual markets, consumer behavior, and market structures.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 15,
    code: 'ENG101',
    name: 'English Literature',
    department: 'English',
    description: 'Survey of major works and authors in English literature.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 16,
    code: 'PSY101',
    name: 'Introduction to Psychology',
    department: 'Psychology',
    description: 'Overview of psychological theories, research, and human behavior.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 17,
    code: 'SOC101',
    name: 'Introduction to Sociology',
    department: 'Sociology',
    description: 'Study of society, social institutions, and social relationships.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 18,
    code: 'POL101',
    name: 'Political Science Fundamentals',
    department: 'Political Science',
    description: 'Basic concepts in political theory, government, and international relations.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 19,
    code: 'LAW101',
    name: 'Introduction to Law',
    department: 'Law',
    description: 'Fundamental principles of law, legal systems, and case studies.',
    createdAt: new Date().toISOString(),
  },
  {
    id: 20,
    code: 'EDU101',
    name: 'Foundations of Education',
    department: 'Education',
    description: 'Historical and philosophical foundations of education and teaching.',
    createdAt: new Date().toISOString(),
  },
]
